linters:
  # TODO: remove the `disable` section
  disable:
    - errcheck
    - ineffassign
    - staticcheck
    - unused
  enable:
    - godot
    - gofmt
    - misspell
    - whitespace
    - gci
linters-settings:
  gci:
    sections:
      - standard
      - default
